[build]
  command = "pip install -r requirements.txt"
  functions = "functions"  # Directory for serverless functions
  publish = "."  # Root directory for static files (optional if no frontend)

# Configure Python runtime for Netlify Functions
[functions]
  [functions.python]
    version = "3.12"


[[redirects]]
  from = "/*"  # Catch all requests
  to = "/.netlify/functions/main"  # Route to the FastAPI handler
  status = 200  # Forward requests (not a redirect)