[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  # publish = "public"

[functions]
  node_bundler = "esbuild" 
  python = "3.12"        

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200 