[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  base = "/"
  # publish = "public"

[functions]
  [functions.python] 
    version = "3.12"  

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200 