[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"  # Directory for serverless functions
  publish = "."  # Root directory for static files (optional if no frontend)

# Configure Python runtime for Netlify Functions
[functions]
  runtime = "python"  # Specify Python runtime
  python_version = "3.12"  # Python version (Netlify supports up to 3.12 as of now)

[[redirects]]
  from = "/*"  # Catch all requests
  to = "/.netlify/functions/main"  # Route to the FastAPI handler
  status = 200  # Forward requests (not a redirect)